version: '3.9'
services:
  api:
    container_name: tictapi
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: node_tictactrip
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/nodemon.json:/home/node/app/nodemon.json
    ports:
      - '4000:4000'
      - '9229:9229'
    command: yarn run dev